# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
      - id: pretty-format-json
        args:
          - '--autofix'
        exclude: Pipfile.lock
      - id: check-yaml
      - id: double-quote-string-fixer
      - id: check-added-large-files
      - id: detect-aws-credentials
        args:
          - --allow-missing-credentials
      - id: detect-private-key
      - id: check-merge-conflict
  - repo: local
    hooks:
      - id: isort
        name: Check python file import order
        entry: make lint-isort
        language: system
        pass_filenames: false
        always_run: true
