name: Publish Release

on:
  release:
    types:
      - published

env:
  DEFAULT_PYTHON_VERSION: 3.11

jobs:
  build-pypi:
    name: Build PyPi 📦
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ITProKyle/action-setup-python@v0.7.0
        with:
          poetry-install: false
      - name: Install Poetry Plugins
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Run Build
        run: make build
      - name: Upload Distribution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist
  publish-pypi:
    name: Publish 📦 To PyPI
    needs:
      - build-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download Distribution Artifact
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist
      - uses: ITProKyle/action-setup-python@v0.7.0
        with:
          poetry-install: false
      - name: Install Poetry Plugins
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Publish Distribution 📦 to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.pypi_password }}
        run: poetry publish
  bump-version:
    name: Bump 📦 Version
    needs:
      - publish-pypi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo (complete)
        uses: actions/checkout@v4
        with:
          ref: master
      - uses: ITProKyle/action-setup-python@v0.7.0
      - name: Install Poetry Plugins
        run: poetry self add "poetry-dynamic-versioning[plugin]"
      - name: Bump Version
        run: poetry dynamic-versioning
      - uses: EndBug/add-and-commit@v9.1.3
        if: github.ref_type == 'tag'
        with:
          add: pyproject.toml
          default_author: github_actions
          message: 'chore: bump version'
          tag: ${{ github.ref_name }}
          tag_push: --force
